unit Pregled;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls, ComCtrls, XPMan, Menus;

type
  TfrmPregled = class(TForm)
    gbPretraga: TGroupBox;
    dd: TLabel;
    ag: TLabel;
    af: TLabel;
    az: TLabel;
    ad: TLabel;
    edMBroj: TEdit;
    lbRezultati: TListBox;
    edIme: TEdit;
    edPrezime: TEdit;
    cbRazred: TComboBox;
    btTrazi: TButton;
    edJMBG: TEdit;
    lbKontrola: TListBox;
    PageControl1: TPageControl;
    Podaci: TTabSheet;
    Raz1: TTabSheet;
    Raz2: TTabSheet;
    Raz3: TTabSheet;
    Raz4: TTabSheet;
    Matura: TTabSheet;
    lblMBroj2: TLabel;
    lblMBroj: TLabel;
    lblIme: TLabel;
    lblPrezime: TLabel;
    lblDatRod: TLabel;
    lblSpol: TLabel;
    lblJMBG: TLabel;
    lblMjRod: TLabel;
    lblDrzRod: TLabel;
    lblDrz: TLabel;
    lblNar: TLabel;
    lblAdresa: TLabel;
    lblImeMajke2: TLabel;
    lblAdresa2: TLabel;
    lblNar2: TLabel;
    lblDrz2: TLabel;
    lblDrzRodj2: TLabel;
    lblMjRodj2: TLabel;
    lblJMBG2: TLabel;
    lblSpol2: TLabel;
    lblDatRod2: TLabel;
    lblPrezime2: TLabel;
    lblIme2: TLabel;
    lblImeMajke: TLabel;
    lblPrezimeMajke: TLabel;
    lblImeOca: TLabel;
    lblPrezimeOca: TLabel;
    lblDatUpisa: TLabel;
    lblVrsta: TLabel;
    lblIsprava: TLabel;
    lblStatus: TLabel;
    lblRazred: TLabel;
    lblRazred2: TLabel;
    lblStatus2: TLabel;
    lblIsprava2: TLabel;
    lblVrsta2: TLabel;
    lblDatUpisa2: TLabel;
    lblPrezimeOca2: TLabel;
    lblImeOca2: TLabel;
    lblPrezimeMajke2: TLabel;
    a: TLabel;
    f: TLabel;
    h: TLabel;
    t: TLabel;
    r: TLabel;
    e: TLabel;
    w: TLabel;
    q: TLabel;
    u: TLabel;
    i: TLabel;
    o: TLabel;
    p: TLabel;
    m: TLabel;
    n: TLabel;
    lblBio: TLabel;
    te: TLabel;
    tw: TLabel;
    tq: TLabel;
    pjezik1: TLabel;
    djezik1: TLabel;
    pdodatni1: TLabel;
    tdodatni1: TLabel;
    pizborni1: TLabel;
    pfakultativni1: TLabel;
    dfakultativni1: TLabel;
    dizborni1: TLabel;
    lblOpravdani: TLabel;
    lblNeopravdani: TLabel;
    Label15: TLabel;
    Label16: TLabel;
    Label17: TLabel;
    ddodatni1: TLabel;
    hrv1: TLabel;
    pjez1: TLabel;
    djez1: TLabel;
    lat1: TLabel;
    grc1: TLabel;
    glz1: TLabel;
    lik1: TLabel;
    psi1: TLabel;
    log1: TLabel;
    fil1: TLabel;
    soc1: TLabel;
    pov1: TLabel;
    zem1: TLabel;
    mat1: TLabel;
    fiz1: TLabel;
    bio1: TLabel;
    inf1: TLabel;
    pig1: TLabel;
    tzk1: TLabel;
    pdod1: TLabel;
    ddod1: TLabel;
    tdod1: TLabel;
    dizb1: TLabel;
    pfak1: TLabel;
    dfak1: TLabel;
    opr1: TLabel;
    neo1: TLabel;
    pizb1: TLabel;
    tekst1: TLabel;
    Label6: TLabel;
    pjezik2: TLabel;
    pjez2: TLabel;
    hrv2: TLabel;
    djez2: TLabel;
    djezik2: TLabel;
    Label12: TLabel;
    lat2: TLabel;
    Label14: TLabel;
    grc2: TLabel;
    glz2: TLabel;
    lik2: TLabel;
    psi2: TLabel;
    log2: TLabel;
    fil2: TLabel;
    soc2: TLabel;
    pov2: TLabel;
    zem2: TLabel;
    mat2: TLabel;
    fiz2: TLabel;
    bio2: TLabel;
    Label30: TLabel;
    Label31: TLabel;
    Label32: TLabel;
    Label33: TLabel;
    Label34: TLabel;
    Label35: TLabel;
    Label36: TLabel;
    Label37: TLabel;
    Label38: TLabel;
    Label39: TLabel;
    Label40: TLabel;
    Label41: TLabel;
    pig2: TLabel;
    inf2: TLabel;
    Label44: TLabel;
    Label45: TLabel;
    pdodatni2: TLabel;
    ddodatni2: TLabel;
    tdodatni2: TLabel;
    tdod2: TLabel;
    ddod2: TLabel;
    pdod2: TLabel;
    tzk2: TLabel;
    Label53: TLabel;
    pizborni2: TLabel;
    dizborni2: TLabel;
    dizb2: TLabel;
    pizb2: TLabel;
    pfak2: TLabel;
    pfakultativni2: TLabel;
    dfak2: TLabel;
    dfakultativni2: TLabel;
    Label62: TLabel;
    Label63: TLabel;
    opr2: TLabel;
    Label65: TLabel;
    Label66: TLabel;
    neo2: TLabel;
    tekst2: TLabel;
    Label69: TLabel;
    pjezik3: TLabel;
    pjez3: TLabel;
    hrv3: TLabel;
    djez3: TLabel;
    djezik3: TLabel;
    Label75: TLabel;
    lat3: TLabel;
    Label77: TLabel;
    grc3: TLabel;
    glz3: TLabel;
    lik3: TLabel;
    psi3: TLabel;
    log3: TLabel;
    fil3: TLabel;
    soc3: TLabel;
    pov3: TLabel;
    zem3: TLabel;
    mat3: TLabel;
    fiz3: TLabel;
    bio3: TLabel;
    Label90: TLabel;
    Label91: TLabel;
    Label92: TLabel;
    Label93: TLabel;
    Label94: TLabel;
    Label95: TLabel;
    Label96: TLabel;
    Label97: TLabel;
    Label98: TLabel;
    Label99: TLabel;
    Label100: TLabel;
    Label101: TLabel;
    pig3: TLabel;
    inf3: TLabel;
    Label104: TLabel;
    Label105: TLabel;
    pdodatni3: TLabel;
    ddodatni3: TLabel;
    tdodatni3: TLabel;
    tdod3: TLabel;
    ddod3: TLabel;
    pdod3: TLabel;
    tzk3: TLabel;
    Label113: TLabel;
    pizborni3: TLabel;
    dizborni3: TLabel;
    dizb3: TLabel;
    pizb3: TLabel;
    pfak3: TLabel;
    pfakultativni3: TLabel;
    dfak3: TLabel;
    dfakultativni3: TLabel;
    Label122: TLabel;
    Label123: TLabel;
    opr3: TLabel;
    Label125: TLabel;
    Label126: TLabel;
    neo3: TLabel;
    tekst3: TLabel;
    Label129: TLabel;
    pjezik4: TLabel;
    pjez4: TLabel;
    hrv4: TLabel;
    djez4: TLabel;
    djezik4: TLabel;
    Label135: TLabel;
    lat4: TLabel;
    Label137: TLabel;
    grc4: TLabel;
    glz4: TLabel;
    lik4: TLabel;
    psi4: TLabel;
    log4: TLabel;
    fil4: TLabel;
    soc4: TLabel;
    pov4: TLabel;
    zem4: TLabel;
    mat4: TLabel;
    fiz4: TLabel;
    bio4: TLabel;
    Label150: TLabel;
    Label151: TLabel;
    Label152: TLabel;
    Label153: TLabel;
    Label154: TLabel;
    Label155: TLabel;
    Label156: TLabel;
    Label157: TLabel;
    Label158: TLabel;
    Label159: TLabel;
    Label160: TLabel;
    Label161: TLabel;
    pig4: TLabel;
    inf4: TLabel;
    Label164: TLabel;
    Label165: TLabel;
    pdodatni4: TLabel;
    ddodatni4: TLabel;
    tdodatni4: TLabel;
    tdod4: TLabel;
    ddod4: TLabel;
    pdod4: TLabel;
    tzk4: TLabel;
    Label173: TLabel;
    pizborni4: TLabel;
    dizborni4: TLabel;
    dizb4: TLabel;
    pizb4: TLabel;
    pfak4: TLabel;
    pfakultativni4: TLabel;
    dfak4: TLabel;
    dfakultativni4: TLabel;
    Label182: TLabel;
    Label183: TLabel;
    opr4: TLabel;
    Label185: TLabel;
    Label186: TLabel;
    neo4: TLabel;
    tekst4: TLabel;
    oslobodjen: TLabel;
    Label7: TLabel;
    Label8: TLabel;
    izborni1: TLabel;
    izborni2: TLabel;
    Label11: TLabel;
    Label13: TLabel;
    Label18: TLabel;
    Label19: TLabel;
    Label20: TLabel;
    naslov: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    od: TLabel;
    doo: TLabel;
    zapisnik: TLabel;
    mat: TLabel;
    hrv: TLabel;
    izb1: TLabel;
    izb2: TLabel;
    rb: TLabel;
    kem1: TLabel;
    kem4: TLabel;
    Label4: TLabel;
    kem2: TLabel;
    Label23: TLabel;
    kem3: TLabel;
    Label24: TLabel;
    arh: TCheckBox;
    Label1: TLabel;
    tekst0: TLabel;
    btPovratak: TButton;
    lblucenik: TLabel;
    Label5: TLabel;
    Label9: TLabel;
    lblklasa: TLabel;
    Label21: TLabel;
    lblUrBroj: TLabel;
    Label25: TLabel;
    procedure btTraziClick(Sender: TObject);
    procedure lbRezultatiClick(Sender: TObject);
    procedure FormActivate(Sender: TObject);
    procedure btPovratakClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frmPregled: TfrmPregled;
  fin,kont,br,velbroj:integer;
  naziv1,naziv2,poc,trazeni,trenutni,nnesto,odaberi,khm1,khm2,helou,umetanje:string;
  nesto:variant;
  nizk:array[1..1000] of string;
  penz:boolean;
implementation

uses Glavna, Prijelaz;

{$R *.dfm}

procedure TfrmPregled.btTraziClick(Sender: TObject);
var kb1,kb2:boolean;
begin
lblucenik.Caption:='Uèenik';
podaci.TabVisible:=false; raz1.TabVisible:=false; raz2.tabVisible:=false; raz3.tabVisible:=false; raz4.tabVisible:=false; Matura.tabVisible:=false;
odaberi:='select * from ucenici where ';
lbRezultati.clear;
lbKontrola.Clear;
if edMBroj.text<>'' then odaberi:=odaberi+'and MBroj='+chr(39)+edMBroj.text+chr(39);
if edIme.text<>'' then odaberi:=odaberi+'and Ime='+chr(39)+edIme.text+chr(39);
if edPrezime.text<>'' then odaberi:=odaberi+'and Prezime='+chr(39)+edPrezime.text+chr(39);
if edJMBG.text<>'' then odaberi:=odaberi+'and JMBG='+chr(39)+edJMBG.text+chr(39);
if cbRazred.text<>'' then odaberi:=odaberi+'and Razred='+chr(39)+cbRazred.text+chr(39);
if length(odaberi)<32 then delete(odaberi,22,7) else delete(odaberi,29,4);
frmglavna.podaci.Close;
frmglavna.podaci.CommandText:=odaberi;
frmglavna.podaci.ExecuteOptions;
frmglavna.podaci.Open;
kb1:=false; kb2:=true;
if frmglavna.podaci.Recordset.RecordCount=0 then kb1:=true;
while not (frmglavna.podaci.Recordset.eof) do begin
  nesto:=frmglavna.podaci.Recordset.fields.item['Prezime'];
  khm1:=nesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Ime'];
  khm2:=nesto;
  naziv1:=khm1+' '+khm2;
  nesto:=frmglavna.podaci.Recordset.fields.item['ID'];
  khm1:=nesto;
  naziv2:=naziv1+'*'+khm1;
  lbRezultati.Items.Add(naziv1);
  lbKontrola.Items.add(naziv2);
  frmglavna.podaci.Recordset.MoveNext;
end;
kb2:=true;
if arh.Checked=true then begin
  odaberi:='select * from Arhiva where ';
  if edMBroj.text<>'' then odaberi:=odaberi+'and MBroj='+chr(39)+edMBroj.text+chr(39);
  if edIme.text<>'' then odaberi:=odaberi+'and Ime='+chr(39)+edIme.text+chr(39);
  if edPrezime.text<>'' then odaberi:=odaberi+'and Prezime='+chr(39)+edPrezime.text+chr(39);
  if edJMBG.text<>'' then odaberi:=odaberi+'and JMBG='+chr(39)+edJMBG.text+chr(39);
  if cbRazred.text<>'' then odaberi:=odaberi+'and Razred='+chr(39)+cbRazred.text[2]+chr(39);
  if length(odaberi)<30 then delete(odaberi,21,6) else delete(odaberi,27,4);
  frmglavna.podaci.Close;
  frmglavna.podaci.CommandText:=odaberi;
  frmglavna.podaci.ExecuteOptions;
  frmglavna.podaci.Open;
  velbroj:=0;
  if frmglavna.podaci.Recordset.RecordCount=0 then kb2:=true else kb2:=false;
  while not (frmglavna.podaci.Recordset.eof) do begin
    velbroj:=velbroj+1;
    nesto:=frmglavna.podaci.Recordset.fields.item['Prezime'];
    khm1:=nesto;
    nesto:=frmglavna.podaci.Recordset.fields.item['Ime'];
    khm2:=nesto;
    naziv1:=khm1+' '+khm2;
    nesto:=frmglavna.podaci.Recordset.fields.item['ID'];
    khm1:=nesto;
    nizk[velbroj]:=khm1;
    naziv2:=naziv1+'*'+khm1;
    lbRezultati.Items.Add(naziv1);
    lbKontrola.Items.add(naziv2);
    frmglavna.podaci.Recordset.MoveNext;
  end;
end;
if (kb1=true) and (kb2=true) then application.MessageBox('Nema rezultata koji zadovoljavaju Vaš upit.', 'Registar - pretraga uèenika', mb_OK);
end;

procedure TfrmPregled.lbRezultatiClick(Sender: TObject);
var brojka,sspol,uspjeh,osl:string;
    vk,uk,c,brojac,i:integer;
    pr:real;
begin
podaci.TabVisible:=true;
poc:=lbKontrola.Items.Strings[lbRezultati.ItemIndex];
trazeni:=copy(poc,pos('*',poc)+1,length(poc)-pos('*',poc));
penz:=false;
for i:=1 to velbroj do if nizk[i]=trazeni then penz:=true;
frmglavna.podaci.Close;
if penz=false then frmglavna.podaci.CommandText:='select * from Ucenici where ID='+trazeni else frmglavna.podaci.CommandText:='select * from Arhiva where ID='+trazeni;
frmglavna.podaci.ExecuteOptions;
frmglavna.podaci.Open;
trenutni:=trazeni;
nesto:=frmglavna.podaci.Recordset.fields.item['MBroj']; nnesto:=nesto;lblMbroj.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Ime']; nnesto:=nesto;lblIme.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Prezime']; nnesto:=nesto;lblPrezime.Caption:=nnesto;
lblucenik.Caption:=lblprezime.Caption+', '+lblime.Caption;
nesto:=frmglavna.podaci.Recordset.fields.item['DatRod']; nnesto:=nesto;lblDatRod.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Spol']; nnesto:=nesto;lblSpol.Caption:=nnesto; sspol:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['JMBG']; nnesto:=nesto;lblJMBG.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['MjRod']; nnesto:=nesto;lblMjRod.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['DrzRod']; nnesto:=nesto;lblDrzRod.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Drz']; nnesto:=nesto;lblDrz.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Nar']; nnesto:=nesto;lblNar.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Adresa']; nnesto:=nesto;lblAdresa.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['ImeMajke']; nnesto:=nesto;lblImeMajke.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['PrezimeMajke']; nnesto:=nesto;lblPrezimeMajke.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['ImeOca']; nnesto:=nesto;lblImeOca.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['PrezimeOca']; nnesto:=nesto;lblPrezimeOca.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['DatUpisa'];nnesto:=nesto; lblDatUpisa.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Vrsta']; nnesto:=nesto;lblVrsta.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Isprava']; nnesto:=nesto;lblIsprava.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Status']; nnesto:=nesto;lblStatus.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['Razred']; nnesto:=nesto;lblRazred.Caption:=nnesto;
if sspol='M' then begin lblimemajke2.Caption:='Sin majke'; lblimeoca2.Caption:='Sin oca'; end;
if sspol='Z' then begin lblimemajke2.Caption:='Kæi majke'; lblimeoca2.Caption:='Kæi oca'; end;

brojka:=nnesto[1];
nesto:=frmglavna.podaci.Recordset.fields.item['Klasa']; nnesto:=nesto;lblklasa.Caption:=nnesto;
nesto:=frmglavna.podaci.Recordset.fields.item['UrBroj']; nnesto:=nesto;lblurbroj.Caption:=nnesto;
if penz=true then begin

  nesto:=frmglavna.podaci.Recordset.fields.item['Matura']; nnesto:=nesto;
  if sspol='M' then tekst0.Caption:='Uèenik je '+nnesto+'. godine završio srednje školovanje.';
  if sspol='Z' then tekst0.Caption:='Uèenica je '+nnesto+'. godine završila srednje školovanje.';
end;

hrv1.caption:='-'; pjez1.caption:='-'; djez1.caption:='-'; lat1.caption:='-'; grc1.caption:='-';
glz1.caption:='-'; lik1.caption:='-'; psi1.caption:='-'; log1.caption:='-'; fil1.caption:='-';
soc1.caption:='-'; pov1.caption:='-'; zem1.caption:='-'; mat1.caption:='-'; fiz1.caption:='-';
kem1.caption:='-'; bio1.caption:='-'; inf1.caption:='-'; pig1.caption:='-'; tzk1.caption:='-';
pdod1.caption:='-'; ddod1.caption:='-'; tdod1.caption:='-'; pizb1.caption:='-'; dizb1.caption:='-';
pfak1.caption:='-'; dfak1.caption:='-'; opr1.caption:='-'; neo1.caption:='-'; pjezik1.Caption:='-';
djezik1.caption:='-'; pdodatni1.caption:='-'; ddodatni1.caption:='-'; tdodatni1.caption:='-'; pizborni1.caption:='-';
dizborni1.caption:='-'; pfakultativni1.caption:='-'; dfakultativni1.caption:='-';

hrv2.caption:='-'; pjez2.caption:='-'; djez2.caption:='-'; lat2.caption:='-'; grc2.caption:='-';
glz2.caption:='-'; lik2.caption:='-'; psi2.caption:='-'; log2.caption:='-'; fil2.caption:='-';
soc2.caption:='-'; pov2.caption:='-'; zem2.caption:='-'; mat2.caption:='-'; fiz2.caption:='-';
kem2.caption:='-'; bio2.caption:='-'; inf2.caption:='-'; pig2.caption:='-'; tzk2.caption:='-';
pdod2.caption:='-'; ddod2.caption:='-'; tdod2.caption:='-'; pizb2.caption:='-'; dizb2.caption:='-';
pfak2.caption:='-'; dfak2.caption:='-'; opr2.caption:='-'; neo2.caption:='-'; pjezik2.caption:='-';
djezik2.caption:='-'; pdodatni2.caption:='-'; ddodatni2.caption:='-'; tdodatni2.caption:='-'; pizborni2.caption:='-';
dizborni2.caption:='-'; pfakultativni2.caption:='-'; dfakultativni2.caption:='-';

hrv3.caption:='-'; pjez3.caption:='-'; djez3.caption:='-'; lat3.caption:='-'; grc3.caption:='-';
glz3.caption:='-'; lik3.caption:='-'; psi3.caption:='-'; log3.caption:='-'; fil3.caption:='-';
soc3.caption:='-'; pov3.caption:='-'; zem3.caption:='-'; mat3.caption:='-'; fiz3.caption:='-';
kem3.caption:='-'; bio3.caption:='-'; inf3.caption:='-'; pig3.caption:='-'; tzk3.caption:='-';
pdod3.caption:='-'; ddod3.caption:='-'; tdod3.caption:='-'; pizb3.caption:='-'; dizb3.caption:='-';
pfak3.caption:='-'; dfak3.caption:='-'; opr3.caption:='-'; neo3.caption:='-'; pjezik3.caption:='-';
djezik3.caption:='-'; pdodatni3.caption:='-'; ddodatni3.caption:='-'; tdodatni3.caption:='-'; pizborni3.caption:='-';
dizborni3.caption:='-'; pfakultativni3.caption:='-'; dfakultativni3.caption:='-';

hrv4.caption:='-'; pjez4.caption:='-'; djez4.caption:='-'; lat4.caption:='-'; grc4.caption:='-';
glz4.caption:='-'; lik4.caption:='-'; psi4.caption:='-'; log4.caption:='-'; fil4.caption:='-';
soc4.caption:='-'; pov4.caption:='-'; zem4.caption:='-'; mat4.caption:='-'; fiz4.caption:='-';
kem4.caption:='-'; bio4.caption:='-'; inf4.caption:='-'; pig4.caption:='-'; tzk4.caption:='-';
pdod4.caption:='-'; ddod4.caption:='-'; tdod4.caption:='-'; pizb4.caption:='-'; dizb4.caption:='-';
pfak4.caption:='-'; dfak4.caption:='-'; opr4.caption:='-'; neo4.caption:='-'; pjezik4.caption:='-';
djezik4.caption:='-'; pdodatni4.caption:='-'; ddodatni4.caption:='-'; tdodatni4.caption:='-'; pizborni4.caption:='-';
dizborni4.caption:='-'; pfakultativni4.caption:='-'; dfakultativni4.caption:='-';

tekst1.Caption:=''; tekst2.Caption:=''; tekst3.Caption:=''; tekst4.Caption:=''; oslobodjen.Caption:='';
naslov.Caption:='-';
mat.caption:='-'; Hrv.caption:='-'; Izb1.caption:='-'; Izb2.caption:='-';  Izborni1.caption:='-';
Izborni2.caption:='-'; Od.caption:='-'; Doo.caption:='-'; Rb.caption:='-'; zapisnik.caption:='-';

raz1.TabVisible:=true; raz2.tabVisible:=true; raz3.tabVisible:=true; raz4.tabVisible:=true; Matura.tabVisible:=true;
if brojka='1' then begin raz2.tabVisible:=false; raz3.tabVisible:=false; raz4.tabVisible:=false; Matura.tabVisible:=false; end;
if brojka='2' then begin raz3.tabVisible:=false; raz4.tabVisible:=false; Matura.tabVisible:=false; end;
if brojka='3' then begin raz4.tabVisible:=false; Matura.tabVisible:=false; end;



frmglavna.podaci.Close;
if brojka='1' then frmglavna.podaci.CommandText:='select * from Kraj where ID='+trazeni else frmglavna.podaci.CommandText:='select * from Ocjene1 where ID='+trazeni;
frmglavna.podaci.ExecuteOptions;
frmglavna.podaci.Open;
trenutni:=trazeni;
uk:=0; brojac:=0;
if frmglavna.podaci.Recordset.eof <> true then begin
  nesto:=frmglavna.podaci.Recordset.fields.item['Hrv']; nnesto:=nesto; if nnesto<>'' then begin Hrv1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['1Jez']; nnesto:=nesto; if nnesto<>'' then  begin pJez1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['2Jez']; nnesto:=nesto; if nnesto<>'' then  begin dJez1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Lat']; nnesto:=nesto; if nnesto<>'' then  begin Lat1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Grc']; nnesto:=nesto; if nnesto<>'' then  begin Grc1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Glz']; nnesto:=nesto; if nnesto<>'' then  begin Glz1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Lik']; nnesto:=nesto; if nnesto<>'' then  begin Lik1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Psi']; nnesto:=nesto; if nnesto<>'' then  begin Psi1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Log']; nnesto:=nesto; if nnesto<>'' then  begin Log1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fil']; nnesto:=nesto; if nnesto<>'' then  begin Fil1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Soc']; nnesto:=nesto; if nnesto<>'' then begin  Soc1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Pov']; nnesto:=nesto; if nnesto<>'' then  begin Pov1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Zem']; nnesto:=nesto; if nnesto<>'' then  begin Zem1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Mat']; nnesto:=nesto; if nnesto<>'' then  begin Mat1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fiz']; nnesto:=nesto; if nnesto<>'' then  begin Fiz1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Kem'];nnesto:=nesto; if nnesto<>'' then  begin Kem1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Bio']; nnesto:=nesto; if nnesto<>'' then  begin Bio1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Inf']; nnesto:=nesto; if nnesto<>'' then  begin Inf1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Pig']; nnesto:=nesto; if nnesto<>'' then  begin Pig1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Tzk']; nnesto:=nesto; if nnesto<>'' then begin  Tzk1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod1']; nnesto:=nesto; if nnesto<>'' then  begin pDod1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod2']; nnesto:=nesto; if nnesto<>'' then  begin dDod1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod3']; nnesto:=nesto; if nnesto<>'' then  begin tDod1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb1']; nnesto:=nesto; if nnesto<>'' then  begin pIzb1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb2']; nnesto:=nesto; if nnesto<>'' then begin  dIzb1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fak1']; nnesto:=nesto; if nnesto<>'' then  begin pFak1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fak2']; nnesto:=nesto; if nnesto<>'' then  begin dFak1.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Opravdani']; nnesto:=nesto; if nnesto<>'' then Opr1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Neopravdani']; nnesto:=nesto; if nnesto<>'' then Neo1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['PrviJezik']; nnesto:=nesto; if nnesto<>'' then pjezik1.Caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['DrugiJezik']; nnesto:=nesto; if nnesto<>'' then djezik1.caption:=nesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni1']; nnesto:=nesto; if nnesto<>'' then pdodatni1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni2']; nnesto:=nesto; if nnesto<>'' then ddodatni1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni3']; nnesto:=nesto; if nnesto<>'' then tdodatni1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni1']; nnesto:=nesto; if nnesto<>'' then pizborni1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni2']; nnesto:=nesto; if nnesto<>'' then dizborni1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fakultativni1']; nnesto:=nesto; if nnesto<>'' then pfakultativni1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fakultativni2']; nnesto:=nesto; if nnesto<>'' then dfakultativni1.caption:=nnesto;
  pr:=uk/brojac;
  uspjeh:='';
  if pr>=4.5 then uspjeh:='odliènim';
  if (pr<4.5) and (pr>=3.5) then uspjeh:='vrlo dobrim';
  if (pr<3.5) and (pr>=2.5) then uspjeh:='dobrim';
  if (pr<2.5) and (pr>=1.5) then uspjeh:='dovoljnim';
  if uspjeh<>'' then begin
    if sspol='M' then tekst1.caption:='Uèenik je s '+uspjeh+' uspjehom završio 1. razred.';
    if sspol='Z' then tekst1.caption:='Uèenica je s '+uspjeh+' uspjehom završila 1. razred.';
  end;
end;
frmglavna.podaci.Close;




frmglavna.podaci.Close;
if brojka='2' then frmglavna.podaci.CommandText:='select * from Kraj where ID='+trazeni;
if (brojka='3') or (brojka='4') or (penz=true) then frmglavna.podaci.CommandText:='select * from Ocjene2 where ID='+trazeni;
frmglavna.podaci.ExecuteOptions;
frmglavna.podaci.Open;
trenutni:=trazeni;
uk:=0; brojac:=0;
if brojka<>'1' then begin
if frmglavna.podaci.Recordset.eof <> true then begin
  nesto:=frmglavna.podaci.Recordset.fields.item['Hrv']; nnesto:=nesto; if nnesto<>'' then begin Hrv2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['1Jez']; nnesto:=nesto; if nnesto<>'' then  begin pJez2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['2Jez']; nnesto:=nesto; if nnesto<>'' then  begin dJez2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Lat']; nnesto:=nesto; if nnesto<>'' then  begin Lat2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Grc']; nnesto:=nesto; if nnesto<>'' then  begin Grc2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Glz']; nnesto:=nesto; if nnesto<>'' then  begin Glz2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Lik']; nnesto:=nesto; if nnesto<>'' then  begin Lik2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Psi']; nnesto:=nesto; if nnesto<>'' then  begin Psi2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Log']; nnesto:=nesto; if nnesto<>'' then  begin Log2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fil']; nnesto:=nesto; if nnesto<>'' then  begin Fil2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Soc']; nnesto:=nesto; if nnesto<>'' then begin  Soc2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Pov']; nnesto:=nesto; if nnesto<>'' then  begin Pov2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Zem']; nnesto:=nesto; if nnesto<>'' then  begin Zem2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Mat']; nnesto:=nesto; if nnesto<>'' then  begin Mat2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fiz']; nnesto:=nesto; if nnesto<>'' then  begin Fiz2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Kem'];nnesto:=nesto; if nnesto<>'' then  begin Kem2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Bio']; nnesto:=nesto; if nnesto<>'' then  begin Bio2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Inf']; nnesto:=nesto; if nnesto<>'' then  begin Inf2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Pig']; nnesto:=nesto; if nnesto<>'' then  begin Pig2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Tzk']; nnesto:=nesto; if nnesto<>'' then begin  Tzk2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod1']; nnesto:=nesto; if nnesto<>'' then  begin pDod2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod2']; nnesto:=nesto; if nnesto<>'' then  begin dDod2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod3']; nnesto:=nesto; if nnesto<>'' then  begin tDod2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb1']; nnesto:=nesto; if nnesto<>'' then  begin pIzb2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb2']; nnesto:=nesto; if nnesto<>'' then begin  dIzb2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fak1']; nnesto:=nesto; if nnesto<>'' then  begin pFak2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fak2']; nnesto:=nesto; if nnesto<>'' then  begin dFak2.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Opravdani']; nnesto:=nesto; if nnesto<>'' then Opr2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Neopravdani']; nnesto:=nesto; if nnesto<>'' then Neo2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['PrviJezik']; nnesto:=nesto; if nnesto<>'' then pjezik2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['DrugiJezik']; nnesto:=nesto; if nnesto<>'' then djezik2.caption:=nesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni1']; nnesto:=nesto; if nnesto<>'' then pdodatni2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni2']; nnesto:=nesto; if nnesto<>'' then ddodatni2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni3']; nnesto:=nesto; if nnesto<>'' then tdodatni2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni1']; nnesto:=nesto; if nnesto<>'' then pizborni2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni2']; nnesto:=nesto; if nnesto<>'' then dizborni2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fakultativni1']; nnesto:=nesto; if nnesto<>'' then pfakultativni2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fakultativni2']; nnesto:=nesto; if nnesto<>'' then dfakultativni2.caption:=nnesto;
  pr:=uk/brojac;
  uspjeh:='';
  if pr>=4.5 then uspjeh:='odliènim';
  if (pr<4.5) and (pr>=3.5) then uspjeh:='vrlo dobrim';
  if (pr<3.5) and (pr>=2.5) then uspjeh:='dobrim';
  if (pr<2.5) and (pr>=1.5) then uspjeh:='dovoljnim';
  if uspjeh<>'' then begin
    if sspol='M' then tekst2.caption:='Uèenik je s '+uspjeh+' uspjehom završio 2. razred.';
    if sspol='Z' then tekst2.caption:='Uèenica je s '+uspjeh+' uspjehom završila 2. razred.';
  end;
end;
end;
frmglavna.podaci.Close;




frmglavna.podaci.Close;
if brojka='3' then frmglavna.podaci.CommandText:='select * from Kraj where ID='+trazeni;
if (brojka='4') or (penz=true) then frmglavna.podaci.CommandText:='select * from Ocjene3 where ID='+trazeni;
frmglavna.podaci.ExecuteOptions;
frmglavna.podaci.Open;
trenutni:=trazeni;
uk:=0; brojac:=0;
if (brojka<>'2') and (brojka<>'1') then begin
if frmglavna.podaci.Recordset.eof <> true then begin
  nesto:=frmglavna.podaci.Recordset.fields.item['Hrv']; nnesto:=nesto; if nnesto<>'' then begin Hrv3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['1Jez']; nnesto:=nesto; if nnesto<>'' then  begin pJez3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['2Jez']; nnesto:=nesto; if nnesto<>'' then  begin dJez3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Lat']; nnesto:=nesto; if nnesto<>'' then  begin Lat3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Grc']; nnesto:=nesto; if nnesto<>'' then  begin Grc3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Glz']; nnesto:=nesto; if nnesto<>'' then  begin Glz3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Lik']; nnesto:=nesto; if nnesto<>'' then  begin Lik3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Psi']; nnesto:=nesto; if nnesto<>'' then  begin Psi3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Log']; nnesto:=nesto; if nnesto<>'' then  begin Log3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fil']; nnesto:=nesto; if nnesto<>'' then  begin Fil3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Soc']; nnesto:=nesto; if nnesto<>'' then begin  Soc3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Pov']; nnesto:=nesto; if nnesto<>'' then  begin Pov3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Zem']; nnesto:=nesto; if nnesto<>'' then  begin Zem3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Mat']; nnesto:=nesto; if nnesto<>'' then  begin Mat3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fiz']; nnesto:=nesto; if nnesto<>'' then  begin Fiz3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Kem'];nnesto:=nesto; if nnesto<>'' then  begin Kem3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Bio']; nnesto:=nesto; if nnesto<>'' then  begin Bio3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Inf']; nnesto:=nesto; if nnesto<>'' then  begin Inf3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Pig']; nnesto:=nesto; if nnesto<>'' then  begin Pig3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Tzk']; nnesto:=nesto; if nnesto<>'' then begin  Tzk3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod1']; nnesto:=nesto; if nnesto<>'' then  begin pDod3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod2']; nnesto:=nesto; if nnesto<>'' then  begin dDod3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod3']; nnesto:=nesto; if nnesto<>'' then  begin tDod3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb1']; nnesto:=nesto; if nnesto<>'' then  begin pIzb3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb2']; nnesto:=nesto; if nnesto<>'' then begin  dIzb3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fak1']; nnesto:=nesto; if nnesto<>'' then  begin pFak3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fak2']; nnesto:=nesto; if nnesto<>'' then  begin dFak3.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Opravdani']; nnesto:=nesto; if nnesto<>'' then Opr3.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Neopravdani']; nnesto:=nesto; if nnesto<>'' then Neo3.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['PrviJezik']; nnesto:=nesto; if nnesto<>'' then pjezik3.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['DrugiJezik']; nnesto:=nesto; if nnesto<>'' then djezik3.caption:=nesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni1']; nnesto:=nesto; if nnesto<>'' then pdodatni3.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni2']; nnesto:=nesto; if nnesto<>'' then ddodatni3.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni3']; nnesto:=nesto; if nnesto<>'' then tdodatni3.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni1']; nnesto:=nesto; if nnesto<>'' then pizborni3.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni2']; nnesto:=nesto; if nnesto<>'' then dizborni3.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fakultativni1']; nnesto:=nesto; if nnesto<>'' then pfakultativni3.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fakultativni2']; nnesto:=nesto; if nnesto<>'' then dfakultativni3.caption:=nnesto;
  pr:=uk/brojac;
  uspjeh:='';
  if pr>=4.5 then uspjeh:='odliènim';
  if (pr<4.5) and (pr>=3.5) then uspjeh:='vrlo dobrim';
  if (pr<3.5) and (pr>=2.5) then uspjeh:='dobrim';
  if (pr<2.5) and (pr>=1.5) then uspjeh:='dovoljnim';
  if uspjeh<>'' then begin
    if sspol='M' then tekst3.caption:='Uèenik je s '+uspjeh+' uspjehom završio 3. razred.';
    if sspol='Z' then tekst3.caption:='Uèenica je s '+uspjeh+' uspjehom završila 3. razred.';
  end;
end;
end;
frmglavna.podaci.Close;


frmglavna.podaci.Close;
if brojka='4' then frmglavna.podaci.CommandText:='select * from Kraj where ID='+trazeni;
if penz=true then frmglavna.podaci.CommandText:='select * from Ocjene4 where ID='+trazeni;
frmglavna.podaci.ExecuteOptions;
frmglavna.podaci.Open;
trenutni:=trazeni;
uk:=0; brojac:=0;
if (brojka='4') or (penz=true) then begin
if frmglavna.podaci.Recordset.eof <> true then begin
  nesto:=frmglavna.podaci.Recordset.fields.item['Hrv']; nnesto:=nesto; if nnesto<>'' then begin Hrv4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['1Jez']; nnesto:=nesto; if nnesto<>'' then  begin pJez4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['2Jez']; nnesto:=nesto; if nnesto<>'' then  begin dJez4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Lat']; nnesto:=nesto; if nnesto<>'' then  begin Lat4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Grc']; nnesto:=nesto; if nnesto<>'' then  begin Grc4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Glz']; nnesto:=nesto; if nnesto<>'' then  begin Glz4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Lik']; nnesto:=nesto; if nnesto<>'' then  begin Lik4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Psi']; nnesto:=nesto; if nnesto<>'' then  begin Psi4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Log']; nnesto:=nesto; if nnesto<>'' then  begin Log4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fil']; nnesto:=nesto; if nnesto<>'' then  begin Fil4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Soc']; nnesto:=nesto; if nnesto<>'' then begin  Soc4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Pov']; nnesto:=nesto; if nnesto<>'' then  begin Pov4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Zem']; nnesto:=nesto; if nnesto<>'' then  begin Zem4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Mat']; nnesto:=nesto; if nnesto<>'' then  begin Mat4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fiz']; nnesto:=nesto; if nnesto<>'' then  begin Fiz4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Kem'];nnesto:=nesto; if nnesto<>'' then  begin Kem4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Bio']; nnesto:=nesto; if nnesto<>'' then  begin Bio4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Inf']; nnesto:=nesto; if nnesto<>'' then  begin Inf4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Pig']; nnesto:=nesto; if nnesto<>'' then  begin Pig4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Tzk']; nnesto:=nesto; if nnesto<>'' then begin  Tzk4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod1']; nnesto:=nesto; if nnesto<>'' then  begin pDod4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod2']; nnesto:=nesto; if nnesto<>'' then  begin dDod4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dod3']; nnesto:=nesto; if nnesto<>'' then  begin tDod4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb1']; nnesto:=nesto; if nnesto<>'' then  begin pIzb4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb2']; nnesto:=nesto; if nnesto<>'' then begin  dIzb4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fak1']; nnesto:=nesto; if nnesto<>'' then  begin pFak4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fak2']; nnesto:=nesto; if nnesto<>'' then  begin dFak4.caption:=nnesto; val(nnesto,vk,c); brojac:=brojac+1; uk:=uk+vk; end;
  nesto:=frmglavna.podaci.Recordset.fields.item['Opravdani']; nnesto:=nesto; if nnesto<>'' then Opr4.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Neopravdani']; nnesto:=nesto; if nnesto<>'' then Neo4.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['PrviJezik']; nnesto:=nesto; if nnesto<>'' then pjezik4.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['DrugiJezik']; nnesto:=nesto; if nnesto<>'' then djezik4.caption:=nesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni1']; nnesto:=nesto; if nnesto<>'' then pdodatni4.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni2']; nnesto:=nesto; if nnesto<>'' then ddodatni4.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Dodatni3']; nnesto:=nesto; if nnesto<>'' then tdodatni4.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni1']; nnesto:=nesto; if nnesto<>'' then pizborni4.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni2']; nnesto:=nesto; if nnesto<>'' then dizborni4.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fakultativni1']; nnesto:=nesto; if nnesto<>'' then pfakultativni4.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Fakultativni2']; nnesto:=nesto; if nnesto<>'' then dfakultativni4.caption:=nnesto;
  pr:=uk/brojac;
  uspjeh:='';
  if pr>=4.5 then uspjeh:='odliènim';
  if (pr<4.5) and (pr>=3.5) then uspjeh:='vrlo dobrim';
  if (pr<3.5) and (pr>=2.5) then uspjeh:='dobrim';
  if (pr<2.5) and (pr>=1.5) then uspjeh:='dovoljnim';
  if uspjeh<>'' then begin
    if sspol='M' then tekst4.caption:='Uèenik je s '+uspjeh+' uspjehom završio 4. razred.';
    if sspol='Z' then tekst4.caption:='Uèenica je s '+uspjeh+' uspjehom završila 4. razred.';
  end;
end;
end;
frmglavna.podaci.Close;




frmglavna.podaci.Close;
if brojka='4' then frmglavna.podaci.CommandText:='select * from Matura where ID='+trazeni;
if penz=true then frmglavna.podaci.CommandText:='select * from ArhivaMat where ID='+trazeni;
frmglavna.podaci.ExecuteOptions;
frmglavna.podaci.Open;
trenutni:=trazeni;
uk:=0; brojac:=0;
if (brojka='4') or (penz=true) then begin
if frmglavna.podaci.Recordset.eof <> true then begin
  nesto:=frmglavna.podaci.Recordset.fields.item['Naslov']; nnesto:=nesto;  if nnesto<>'' then Naslov.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Mat']; nnesto:=nesto;  if nnesto<>''  then mat.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Hrv']; nnesto:=nesto;  if nnesto<>''  then Hrv.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb1']; nnesto:=nesto; if nnesto<>''  then  Izb1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izb2']; nnesto:=nesto; if nnesto<>''  then  Izb2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni1']; nnesto:=nesto; if nnesto<>''   then Izborni1.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Izborni2']; nnesto:=nesto;  if nnesto<>''  then Izborni2.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Od']; nnesto:=nesto; if nnesto<>''   then Od.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Do']; nnesto:=nesto;  if nnesto<>'' then  Doo.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['RBroj']; nnesto:=nesto;  if nnesto<>''  then Rb.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Zapisnik']; nnesto:=nesto; if nnesto<>''   then zapisnik.caption:=nnesto;
  nesto:=frmglavna.podaci.Recordset.fields.item['Osl']; nnesto:=nesto; if nnesto<>'' then  osl:=nnesto;
  if osl='DA' then begin
    if sspol='M' then oslobodjen.caption:='Uèenik je osloboðen polaganja mature.';
    if sspol='Z' then oslobodjen.caption:='Uèenica je osloboðena polaganja mature.';
  end;
end;
end;
frmglavna.podaci.Close;



end;

procedure TfrmPregled.FormActivate(Sender: TObject);
begin
frmGlavna.Caption:='Registar - Pregled podataka i ocjena uèenika';
cbrazred.Clear;

frmglavna.podaci3.Close;
frmglavna.podaci3.CommandText:='select * from Razredi order by ime';
frmglavna.podaci3.ExecuteOptions;
frmglavna.podaci3.Open;
frmglavna.podaci3.Recordset.MoveFirst;
while not (frmglavna.podaci3.Recordset.eof) do begin
  nesto:=frmglavna.podaci3.Recordset.fields.item['Ime'].value; if nesto<> null then nnesto:=nesto;
  if nnesto<>'' then cbrazred.Items.add(nnesto);
  frmglavna.podaci3.Recordset.MoveNext;
end;
frmglavna.podaci3.close;
cbrazred.Clear;
lbkontrola.Clear;
lbrezultati.Clear;
lblucenik.Caption:='Uèenik';
podaci.TabVisible:=false; raz1.TabVisible:=false; raz2.tabVisible:=false; raz3.tabVisible:=false; raz4.tabVisible:=false; Matura.tabVisible:=false;
edMbroj.Text:='';edIme.Text:='';edPrezime.Text:='';
edJMBG.Text:='';

end;

procedure TfrmPregled.btPovratakClick(Sender: TObject);
begin
frmGlavna.Caption:='Registar';
frmPrijelaz.FormStyle:=fsMDIChild;
frmPrijelaz.WindowState:=wsMaximized;

end;

end.

